name: Build and push Osiguranje-Front to GHCR

on:
  push:
    branches:
      - 'master'

concurrency: ci-${{ github.ref }}

jobs:
  build-and-push:
    name: Build and push Osiguranje-Front image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Osiguranje-Front image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/frontend:latest

      - name: Build and push Osiguranje-Front Kubernetes image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          file: Dockerfilek8s
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/frontend-k8s:latest